### ISSUE TITLE
Pair Programing

### ISSUE THREAD

**Issue by wenshilanR** [JoyfulTechLauncher/joyfulfrugalista#39]
From shadow team: Regularly rotate pairing coding partners to foster broader knowledge sharing about program and reduce dependency on any single team member.

**Comment by JunyiLi0804** [comment]
That makes sense, and we'll consider rotating it regularly

**Comment by JinyuChu09** [comment]
![Image](https://github.com/JoyfulTechLauncher/joyfulfrugalista/assets/140882701/115d94ec-d2a4-422d-bc68-94017e363783)

For complex issues, they worked in pairs and analyse the problem together in Discord. eg. Issue #49 solved by @Jianxing151 @wenshilanR
