### ISSUE TITLE
Fix AddPage header

### ISSUE THREAD

**Issue by wenshilanR** [JoyfulTechLauncher/joyfulfrugalista#49]
Fix the inconsistent style issue and calculator display on the AddPage

<img width="381" alt="AddPage" src="https://github.com/JoyfulTechLauncher/joyfulfrugalista/assets/90823176/a3ddfddf-75e7-4089-b559-f2630c88288b">

**Comment by Jianxing151** [comment]
This seems to be caused by an inconsistency in the size of the interface, and I'll fix that right away.

**Comment by wenshilanR** [comment]
Close as completed.
